
2025-09-10 05:36:14,936 - ERROR - Exception on /edit_profile [POST] [in C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py : 875]
Traceback (most recent call last):
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\app\profile\user_profile.py", line 32, in edit_profile
    abort
NameError: name 'abort' is not defined
2025-09-10 05:36:15,433 - ERROR - Unhandled exception [in C:\Users\oresh\flask_blog\oresh-blog\app\errors\routes.py : 14]
Traceback (most recent call last):
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\app\profile\user_profile.py", line 32, in edit_profile
    abort
NameError: name 'abort' is not defined
2025-09-10 06:01:42,782 - ERROR - Exception on /edit_profile [POST] [in C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py : 875]
Traceback (most recent call last):
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\app\profile\user_profile.py", line 32, in edit_profile
    abort
NameError: name 'abort' is not defined
2025-09-10 06:01:43,167 - ERROR - Exception on /edit_profile [POST] [in C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py : 875]
Traceback (most recent call last):
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\app\profile\user_profile.py", line 32, in edit_profile
    abort
NameError: name 'abort' is not defined
2025-09-10 06:01:43,303 - ERROR - Unhandled exception [in C:\Users\oresh\flask_blog\oresh-blog\app\errors\routes.py : 14]
Traceback (most recent call last):
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\app\profile\user_profile.py", line 32, in edit_profile
    abort
NameError: name 'abort' is not defined
2025-09-10 06:01:43,961 - ERROR - Unhandled exception [in C:\Users\oresh\flask_blog\oresh-blog\app\errors\routes.py : 14]
Traceback (most recent call last):
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\oresh\flask_blog\oresh-blog\app\profile\user_profile.py", line 32, in edit_profile
    abort
NameError: name 'abort' is not defined
2025-09-10 06:04:24,050 - WARNING - Registration form failed to validate: {'password2': ['Passwords must match.']} [in C:\Users\oresh\flask_blog\oresh-blog\app\auth\authentication.py : 18]
2025-09-10 06:04:29,551 - INFO - Registering new user: username=Oreshkin, email=ermolov.jen@yandex.ru, phone=+79010993904 [in C:\Users\oresh\flask_blog\oresh-blog\app\auth\authentication.py : 25]
2025-09-10 06:04:48,153 - WARNING - Registration form failed to validate: {'username': ['This username is already taken.'], 'password2': ['Passwords must match.']} [in C:\Users\oresh\flask_blog\oresh-blog\app\auth\authentication.py : 18]
2025-09-23 16:13:30,316 - WARNING - Registration form failed to validate: {'username': ['This username is already taken.'], 'email': ['This email is already registered.'], 'phone': ['This phone number is already registered.']} [in C:\Users\oresh\flask_blog\oresh-blog\app\auth\authentication.py : 18]
2025-09-23 16:13:48,421 - INFO - Registering new user: username=Oreshkin2, email=zermolov@gmail.com, phone=+79083249078 [in C:\Users\oresh\flask_blog\oresh-blog\app\auth\authentication.py : 25]
2025-09-27 17:48:03,650 - WARNING - Registration form failed to validate: {'username': ['This field is required.'], 'email': ['Invalid email address.'], 'phone': ['This field is required.'], 'password': ['This field is required.'], 'password2': ['This field is required.']} [in C:\Users\oresh\flask_blog\oresh-blog\app\auth\authentication.py : 18]
2025-09-27 18:41:16,993 - INFO - Registering new user: username=fsdf, email=adsfsd@yandex.ru, phone=79010993901 [in C:\Users\oresh\flask_blog\oresh-blog\app\auth\authentication.py : 25]
2025-09-27 23:35:03,548 - WARNING - Registration form failed to validate: {'email': ['This field is required.'], 'phone': ['This field is required.'], 'password': ['This field is required.'], 'password2': ['This field is required.']} [in C:\Users\oresh\flask_blog\oresh-blog\app\auth\authentication.py : 18]
2025-09-27 23:46:23,035 - WARNING - Registration form failed to validate: {'username': ['This username is already taken.']} [in C:\Users\oresh\flask_blog\oresh-blog\app\auth\authentication.py : 18]
